# 上下文初始化加载
info:
  name: spring-cloud-feign

server:
  port: 8081

# 配置eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

# 不开启熔断机制
feign:
  hystrix:
    enabled: false

ribbon:
  # 开启eureka与ribbon的集成
  eureka:
    enabled: true
  # 暂不开启熔断机制
  hystrix:
    enabled: false
  
  